### ISSUE TITLE
query返回的时候也加上一个action吧

### ISSUE THREAD

**Issue by clarkok** [clarkok/database_project#1]
返回的时候就像这样：

``` Javascript
socket.emit('query', {
  action: 'query',
  data: [Object, Object, Object, ...]
})
```

**Comment by MForever78** [comment]
@clarkok 

加了，测试一下？

另外我应该怎么用 socket.io 测试？我现在都是直接调用数据库查询函数，所以即使测试过了也感觉不能保证正确...

**Comment by clarkok** [comment]
访问我的前端然后再控制台里s.emit就好了，我暴露了一个s对象，是socket.io的connection
On Apr 15, 2015 17:24, Tong Xingang notifications@github.com wrote:加了，测试一下？

另外我应该怎么用 socket.io 测试？我现在都是直接调用数据库查询函数，所以即使测试过了也感觉不能保证正确...

**Comment by MForever78** [comment]
现在 Master 分支上面好像是没有你说的这个 s 对象的，可能是你本地改动还没有 Push 上来？

另外这个功能我这边看已经没问题了，你测试好了就 close 吧
