### ISSUE TITLE
list_card 报错了

### ISSUE THREAD

**Issue by clarkok** [clarkok/database_project#3]
![2015-04-17 3 02 15](https://cloud.githubusercontent.com/assets/3633328/7197368/c8c40594-e512-11e4-899b-3ec4cd43f417.png)

**Comment by MForever78** [comment]
这个是因为没有登陆，不允许 list card.

另外如果出现这样的错误我的操作是 emit 你的 error 这个 event ，你看这样可以吗，还是需要改动？

**Comment by clarkok** [comment]
呃我登陆了…… 操作流程是这样的：

点login
登陆成功
控制台里

``` Javascript
s.emit('query', {
  action: 'query',
  data: {
    conditions: []
  }
});
```

**Comment by MForever78** [comment]
是我的错...

修复了，测试通过。
