### ISSUE TITLE
new book 一直报 Column 'stock' cannot be null

### ISSUE THREAD

**Issue by clarkok** [clarkok/database_project#6]
然后我确保 stock 不是 null

以及好像不能 socket.emit('error', ...) 似乎是跟默认的冲突了？

![untitled](https://cloud.githubusercontent.com/assets/3633328/7225493/b40012e0-e771-11e4-984f-b687548a5cb9.png)

**Comment by MForever78** [comment]
是这样的... 新书入库的时候默认操作是 `stock = data.total` 所以你看看 total 是不是 null ？

**Comment by MForever78** [comment]
这是其中一个 Constraint ，还有挺多的... 我应该整理到文档里的，稍后放进去

**Comment by clarkok** [comment]
呃我也做了 stock = data.total ……

我 commit 了一次，登陆后点那个 New Book 填好了之后点 Submit，console 里面会 log 出来 emit 的 data 中的唯一一个 Object，你测试一下看看

**Comment by MForever78** [comment]
噢我查出来了，是我这边的问题。我默认认为你只会提交过来一本书，所以 `data` 应该是

``` js
var data = {
  title: "abc",
  stock: 1,
  total: 1
}
```

这样，而不是一个 array。我觉得前端操作的话没办法批量添加？我这里改也行，你改也行，你决定吧 :)

**Comment by clarkok** [comment]
我改吧，改掉了
